#
# To build a Conda package, run conda build as:
#
#    conda build .
#

package:
  name: lsst-product-configs
  version: &package_version 1.0.1925

build:
  number: 0
  string: "0"

source:
  git_tag: master
  git_url: https://github.com/jhoblitt/legacy_configs.git

requirements:
  build:
    - python
    - eups

  run:
    - python
    - eups

about:
  home: https://github.com/mjuric/legacy_configs
  license: GPLv2
  summary: EUPS product configs for products that are distributed with Anaconda
